apiVersion : apps/v1
kind: Deployment
metadata:
  name: "clusterpolinaask-a8d6"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "clusterpolinaask-a8d6"
  template:
    metadata:
      labels:
        app: "clusterpolinaask-a8d6"
    spec:
      containers:
        - name: "clusterpolinaask-a8d6"
          image: "polinademo232.azurecr.io/clusterpolinaask"
          ports:
          - containerPort: 80