on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: polinademo232.azurecr.io
        username: ${{ secrets.acr_polinademo232_username }}
        password: ${{ secrets.acr_polinademo232_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t polinademo232.azurecr.io/clusterpolinaask:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push polinademo232.azurecr.io/clusterpolinaask:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_clusterpolinaask_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep clusterpolinaask8e5b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace clusterpolinaask8e5b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: clusterpolinaask8e5b
        container-registry-url: polinademo232.azurecr.io
        container-registry-username: ${{ secrets.acr_polinademo232_username }}
        container-registry-password: ${{ secrets.acr_polinademo232_password }}
        secret-name: clusterpolindockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: clusterpolinaask8e5b
        manifests: |
          manifests/deployment-6.yml
          manifests/service-6.yml
        images: |
          polinademo232.azurecr.io/clusterpolinaask:${{ github.sha }}
        imagepullsecrets: |
          clusterpolindockerauth
